"""Added columns.

Revision ID: 903ea0f73db3
Revises: a60ec53b367f
Create Date: 2024-10-01 17:20:05.474926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '903ea0f73db3'
down_revision: Union[str, None] = 'a60ec53b367f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.drop_column('user', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fist_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
