"""severity data type change

Revision ID: 91e69b2c8e68
Revises: ca4d0d49dadd
Create Date: 2024-10-06 16:11:44.352292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91e69b2c8e68'
down_revision: Union[str, None] = 'ca4d0d49dadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'severity',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('LOW', 'NORMAL', 'HIGTH', 'IMMEDIATE', name='type_severity'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'severity',
               existing_type=sa.Enum('LOW', 'NORMAL', 'HIGTH', 'IMMEDIATE', name='type_severity'),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
