"""severity data type change

Revision ID: ca4d0d49dadd
Revises: 98856d0a5e10
Create Date: 2024-10-06 15:53:21.541652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca4d0d49dadd'
down_revision: Union[str, None] = '98856d0a5e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'severity',
               existing_type=mysql.ENUM('LOW', 'NORMAL', 'HIGTH', 'IMMEDIATE'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'severity',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('LOW', 'NORMAL', 'HIGTH', 'IMMEDIATE'),
               existing_nullable=True)
    # ### end Alembic commands ###
